---
pgadmin_container_name: 'pgadmin'
pgadmin_container_port: 80
pgadmin_default_email: 'admin@example.com'
pgadmin_enable_podman: true
pgadmin_firewalld_manage: true
pgadmin_image: 'docker.io/dpage/pgadmin4:latest'
pgadmin_listen_port: 5050
pgadmin_volume_name: 'pgadmin-data'
