---
all:
  hosts:
    lnx01:
      ansible_host: 192.168.1.201

    lnx02:
      ansible_host: 192.168.1.202

    lnx150:
      ansible_host: 192.168.1.150

  children:
    # Environments
    dev:
      vars:
        env_name: 'DEV'
      hosts:
        lnx01:
          ansible_host: 192.168.1.201

        lnx02:
          ansible_host: 192.168.1.202

        lnx150:
          ansible_host: 192.168.1.150  

    prod:
      vars:
        env_name: 'PROD'
      hosts: {}

    postgresql:
      hosts:
        lnx02:
          ansible_host: 192.168.1.202

    podman:
      hosts:
        lnx01:
          ansible_host: 192.168.1.201

    gitea:
      hosts:
        lnx01:
          ansible_host: 192.168.1.201

    pgadmin:
      hosts:
        lnx01:
          ansible_host: 192.168.1.201

    local:
      hosts:
        127.0.0.1:
          ansible_connection: local

    pihole:
      hosts:
        lnx150:
          ansible_host: 192.168.1.150  
