---
all:
  hosts:
    lnx101:
      ansible_host: 192.168.50.101

    lnx102:
      ansible_host: 192.168.50.102

    lnx150:
      ansible_host: 192.168.50.150

  children:
    # Environments
    dev:
      vars:
        env_name: 'DEV'
      hosts:
        lnx101:
          ansible_host: 192.168.50.101

        lnx102:
          ansible_host: 192.168.50.102

        lnx150:
          ansible_host: 192.168.50.150  

    prod:
      vars:
        env_name: 'PROD'
      hosts: {}

    postgresql:
      hosts:
        lnx102:
          ansible_host: 192.168.50.102

    podman:
      hosts:
        lnx101:
          ansible_host: 192.168.50.101

    gitea:
      hosts:
        lnx101:
          ansible_host: 192.168.50.101

    pgadmin:
      hosts:
        lnx101:
          ansible_host: 192.168.50.101

    local:
      hosts:
        127.0.0.1:
          ansible_connection: local

    pihole:
      hosts:
        lnx150:
          ansible_host: 192.168.50.150  
