---
all:
  hosts:
    lnx01:
      ansible_host: 127.0.0.1
      ansible_port: 2222
    

  children:

# Environments

    dev:
      vars:
        env_name: DEV
      hosts:
        lnx01:

    prod:
      vars:
        env_name: PROD
      hosts:
    
# this is host machine
    windows:
      hosts:
        win01:
          ansible_host: 192.168.1.200
          ansible_user: aglu
          ansible_password: ""
          ansible_winrm_server_cert_validation: ignore
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_scheme: http
          ansible_port: 5985
        