---
- name: "=== PODMAN role started ==="
  ansible.builtin.debug:
    msg: "Starting PODMAN role on {{ inventory_hostname }} (env={{ env_name | default('N/A') }})"

- name: Ensure play run on RHEL-family OS (Rocky/RHEL/Alma/CentOS/Fedora)
  ansible.builtin.assert:
    that:
      - ansible_facts["os_family"] == "RedHat"
    fail_msg: "podman role currently supports RHEL-family only."
    success_msg: "RHEL-family detected."

- name: Install base packages for podman
  ansible.builtin.dnf:
    name: "{{ podman_package_list }}"
    state: present
    update_cache: true

- name: Ensure podman group exists
  ansible.builtin.group:
    name: "{{ podman_group }}"
    state: present

- name: Ensure non-interactive podman user exists
  ansible.builtin.user:
    name: "{{ podman_user }}"
    group: "{{ podman_group }}"
    home: "{{ podman_home }}"
    comment: "Service account for running rootless Podman containers"
    create_home: true
    system: true
    shell: /sbin/nologin
    state: present

- name: Ensure subuid mapping exists
  ansible.builtin.lineinfile:
    path: /etc/subuid
    create: true
    regexp: "^{{ podman_user }}:"
    line: "{{ podman_user }}:{{ podman_subuid_start }}:{{ podman_subuid_count }}"
    state: present


- name: Ensure subgid mapping exists
  ansible.builtin.lineinfile:
    path: /etc/subgid
    create: true
    regexp: "^{{ podman_user }}:"
    line: "{{ podman_user }}:{{ podman_subuid_start }}:{{ podman_subuid_count }}"
    state: present

- name: Create Quadlet directory for "{{ podman_user }}" user
  ansible.builtin.file:
    path: "{{ podman_home }}/.config/containers/systemd"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_group }}"
    mode: "0755"
  when: podman_prepare_quadlet_dir | bool

- name: Enable linger for podman user (so user services run at boot)
  ansible.builtin.command: "loginctl enable-linger {{ podman_user }}"
  register: linger_result
  changed_when: linger_result.rc == 0
  failed_when: false
  when: podman_enable_linger | bool

- name: Test podman user created 
  ansible.builtin.command: "podman info --debug"
  become: true
  become_user: "{{ podman_user }}"
  changed_when: false

- name: Deploy Gitea container
  ansible.builtin.import_tasks: gitea.yml
  when: gitea_enable_podman | bool