---
- name: 'Display role start message'
  ansible.builtin.debug:
    msg: 'Starting role on {{ inventory_hostname }} (env={{ env_name | default("N/A") }})'

- name: Ensure play runs on RHEL-family OS
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == 'RedHat'
    fail_msg: 'Role supports RHEL-family only.'
    success_msg: 'RHEL-family detected.'

- name: Install base packages for podman
  ansible.builtin.dnf:
    name: '{{ podman_package_list }}'
    state: present
    update_cache: true

- name: Install optional packages for podman
  ansible.builtin.dnf:
    name: '{{ podman_optional_packages }}'
    state: present
    update_cache: true
  changed_when: podman_optional_result.changed | default(false)
  failed_when: false
  register: podman_optional_result
  when: podman_optional_packages | length > 0

- name: Ensure podman group exists
  ansible.builtin.group:
    name: '{{ podman_group }}'
    state: present

- name: Ensure non-interactive podman user exists
  ansible.builtin.user:
    name: '{{ podman_user }}'
    group: '{{ podman_group }}'
    home: '{{ podman_home }}'
    comment: 'Service account for running rootless Podman containers'
    create_home: true
    system: true
    shell: /sbin/nologin
    state: present

- name: Ensure podman remote temp directory exists
  ansible.builtin.file:
    path: '{{ podman_remote_tmp }}'
    state: directory
    owner: '{{ podman_user }}'
    group: '{{ podman_group }}'
    mode: '0700'

- name: Ensure subuid mapping exists
  ansible.builtin.lineinfile:
    path: /etc/subuid
    create: true
    regexp: '^{{ podman_user }}:'
    line: '{{ podman_user }}:{{ podman_subuid_start }}:{{ podman_subuid_count }}'
    state: present

- name: Ensure subgid mapping exists
  ansible.builtin.lineinfile:
    path: /etc/subgid
    create: true
    regexp: '^{{ podman_user }}:'
    line: '{{ podman_user }}:{{ podman_subuid_start }}:{{ podman_subuid_count }}'
    state: present

- name: 'Create Quadlet directory for {{ podman_user }} user'
  ansible.builtin.file:
    path: '{{ podman_home }}/.config/containers/systemd'
    state: directory
    owner: '{{ podman_user }}'
    group: '{{ podman_group }}'
    mode: '0755'
  when: podman_prepare_quadlet_dir | bool

- name: Enable linger for podman user (so user services run at boot)
  ansible.builtin.command:
    cmd: 'loginctl enable-linger {{ podman_user }}'
  changed_when: linger_result.rc == 0
  failed_when: false
  register: linger_result
  when: podman_enable_linger | bool

- name: Verify podman user can run podman
  ansible.builtin.command:
    cmd: 'podman info --debug'
  become: true
  become_user: '{{ podman_user }}'
  changed_when: false
  vars:
    ansible_remote_tmp: '{{ podman_remote_tmp }}'

- name: Deploy Gitea container
  ansible.builtin.import_tasks: 'gitea.yaml'
  when: gitea_enable_podman | bool
