---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart banner service
  ansible.builtin.systemd:
    name: update-issue.service
    state: restarted

- name: Run banner update now
  ansible.builtin.command: /usr/local/bin/update-issue.sh
  changed_when: true

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted