---
- name: Enable Hyper-V (including management tools)
  ansible.windows.win_feature:
    name:
      - Hyper-V
      - Hyper-V-Tools
      - Hyper-V-PowerShell
    state: present
    include_management_tools: true
  register: hv_features

- name: Reboot if required after enabling Hyper-V
  ansible.windows.win_reboot:
    msg: "Reboot required after enabling Hyper-V features"
  when: hv_features.reboot_required

- name: Ensure Hyper-V default folders exist
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ hyperv_vm_path }}"

- name: Set Hyper-V default VM paths
  ansible.windows.win_shell: |
    $ErrorActionPreference = "Stop"
    Set-VMHost -VirtualMachinePath "{{ win_hv_vm_path }}" -VirtualHardDiskPath "{{ win_hv_vhd_path }}"
  args:
    executable: pwsh.exe