---
postgresql_data_dir: /var/lib/pgsql/data
postgresql_firewalld_manage: true
postgresql_listen_address: '{{ ansible_default_ipv4.address }}'
postgresql_listen_port: 5432
postgresql_module_profile: 'server'
postgresql_module_stream: '16'
postgresql_packages:
  - 'postgresql-server'
