---
# Quadlet
podman_enable_linger: true
podman_group: '{{ podman_user }}'
podman_home: /opt/podman
podman_optional_packages:
  - 'podman-quadlet'
podman_package_list:
  - 'buildah'
  - 'containers-common'
  - 'fuse-overlayfs'
  - 'podman'
  - 'podman-docker'
  - 'policycoreutils-python-utils'
  - 'shadow-utils'
  - 'skopeo'
  - 'slirp4netns'
  - 'systemd-container'
podman_prepare_quadlet_dir: true
podman_remote_tmp: /tmp/ansible-podman

# Rootless mapping range
podman_subuid_count: 65536
podman_subuid_start: 100000
podman_user: 'podman'
