---
- name: Reexec user systemd (quadlet generators)
  ansible.builtin.command: systemctl --user daemon-reexec
  become: true
  become_user: "{{ podman_user }}"
  environment: "{{ podman_user_env }}"
  changed_when: true

- name: Reload user systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
  become: true
  become_user: "{{ podman_user }}"
  environment: "{{ podman_user_env }}"